# KAGGLE CSV CALLS

In [1]:
import os
import pandas as pd
import re

# Define the path to the folder containing the CSV files
folder_path = 'kaggle_renewable' # NOTE: you might need to change this given Teams folder structure

# Create an empty dictionary to store dataframes
dataframes = {}

# Loop through all the CSV files in the folder and save them as pandas dataframes
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):
        # Remove ".csv", replace spaces and dashes with underscores
        df_name = os.path.splitext(filename)[0].replace(' ', '_').replace('-', '_')
        # Remove leading numbers and hyphens if present (e.g., "12-")
        df_name = re.sub(r'^\d+_', '', df_name)
        # Append "_df" at the end of the dataframe name
        df_name += '_df'
        # Read the CSV file into a pandas dataframe
        df = pd.read_csv(os.path.join(folder_path, filename))
        # Store the dataframe in the dictionary
        dataframes[df_name] = df
        # Dynamically assign each dataframe to a global variable
        globals()[df_name] = df

# Perform outer joins on all dataframes
master_df = None

# Join on the keys ['Entity', 'Code', 'Year']
join_keys = ['Entity', 'Code', 'Year']

# Iteratively merge all dataframes while avoiding duplicate join keys
for df_name, df in dataframes.items():
    if master_df is None:
        master_df = df
    else:
        # Perform an outer join on the specified join keys
        master_df = pd.merge(master_df, df, on=join_keys, how='outer', suffixes=('', '_drop'))
        # Drop any duplicate columns that were joined
        master_df = master_df[[col for col in master_df.columns if not col.endswith('_drop')]]

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
master_df.head()

,Entity,Code,Year,Geo Biomass Other - TWh,Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Electricity from solar (TWh),Solar Capacity,Geothermal Capacity,Solar (% electricity),Wind (% electricity),Hydro (% equivalent primary energy),Solar (% equivalent primary energy),Renewables (% equivalent primary energy),Wind (% equivalent primary energy),Electricity from hydro (TWh),Biofuels Production - TWh - Total,Electricity from wind (TWh),Other renewables including bioenergy (TWh),Wind Capacity,Hydro (% electricity),Renewables (% electricity)
0,Africa,NaN,1971,0.164,0.0,0.0,26.013390,0.0,NaN,NaN,NaN,NaN,8.076341,0.0,8.131308,0.0,26.013390,NaN,0.0,0.164,NaN,NaN,NaN
1,Africa,NaN,1972,0.165,0.0,0.0,29.633196,0.0,NaN,NaN,NaN,NaN,8.695498,0.0,8.747766,0.0,29.633196,NaN,0.0,0.165,NaN,NaN,NaN
2,Africa,NaN,1973,0.170,0.0,0.0,31.345707,0.0,NaN,NaN,NaN,NaN,8.492557,0.0,8.542279,0.0,31.345707,NaN,0.0,0.170,NaN,NaN,NaN
3,Africa,NaN,1974,0.175,0.0,0.0,35.667076,0.0,NaN,NaN,NaN,NaN,9.219236,0.0,9.268067,0.0,35.667076,NaN,0.0,0.175,NaN,NaN,NaN
4,Africa,NaN,1975,0.172,0.0,0.0,37.717968,0.0,NaN,NaN,NaN,NaN,9.193146,0.0,9.238402,0.0,37.717968,NaN,0.0,0.172,NaN,NaN,NaN

In [3]:
broad_category_df = master_df[master_df['Code'].isnull()]

# Get distinct values from the 'Entity' column where 'Code' is null
distinct_broad_categories = broad_category_df['Entity'].unique()

# Print the list of distinct entities
print(distinct_broad_categories)

['Africa' 'Africa (BP)' 'Asia' 'Asia Pacific (BP)' 'CIS (BP)'
 'Central America (BP)' 'Eastern Africa (BP)' 'Europe' 'Europe (BP)'
 'European Union (27)' 'High-income countries'
 'Lower-middle-income countries' 'Middle Africa (BP)' 'Middle East (BP)'
 'Non-OECD (BP)' 'North America' 'North America (BP)' 'OECD (BP)'
 'Oceania' 'South America' 'South and Central America (BP)'
 'Upper-middle-income countries' 'Western Africa (BP)' 'Africa (Ember)'
 'Asia (Ember)' 'Europe (Ember)' 'European Union (27) (Ember)'
 'G20 (Ember)' 'G7 (Ember)' 'Latin America and Caribbean (Ember)'
 'Low-income countries' 'North America (Ember)' 'OECD (Ember)'
 'Oceania (Ember)' 'Asia Pacific' 'CIS' 'Other Europe'
 'Other South & Central America' 'South & Central America']

In [5]:
countries_df = master_df[master_df['Code'].notnull()]

# Get distinct values from the 'Entity' column where 'Code' is null
distinct_countries = countries_df['Entity'].unique()

# Print the list of distinct entities
print(distinct_countries)

['Algeria' 'Argentina' 'Australia' 'Austria' 'Azerbaijan' 'Bangladesh'
 'Belarus' 'Belgium' 'Brazil' 'Bulgaria' 'Canada' 'Chile' 'China'
 'Colombia' 'Croatia' 'Cyprus' 'Czechia' 'Denmark' 'Ecuador' 'Egypt'
 'Estonia' 'Finland' 'France' 'Germany' 'Greece' 'Hong Kong' 'Hungary'
 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy'
 'Japan' 'Kazakhstan' 'Kuwait' 'Latvia' 'Lithuania' 'Luxembourg'
 'Malaysia' 'Mexico' 'Morocco' 'Netherlands' 'New Zealand'
 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Saudi Arabia' 'Singapore'
 'Slovakia' 'Slovenia' 'South Africa' 'South Korea' 'Spain' 'Sri Lanka'
 'Sweden' 'Switzerland' 'Taiwan' 'Thailand' 'Trinidad and Tobago' 'Turkey'
 'Turkmenistan' 'USSR' 'Ukraine' 'United Arab Emirates' 'United Kingdom'
 'United States' 'Uzbekistan' 'Venezuela' 'Vietnam' 'World' 'Afghanistan'
 'Albania' 'American Samoa' 'Angola' 'Antigua and Barbuda' 'Armenia'
 'Aruba' 'Bahamas' 'Bahrain' 'Barbados' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana'
 'British Virgin Islands' 'Brunei' 'Burkina Faso' 'Burundi' 'Cambodia'
 'Cameroon' 'Cape Verde' 'Cayman Islands' 'Central African Republic'
 'Chad' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica' "Cote d'Ivoire"
 'Cuba' 'Democratic Republic of Congo' 'Djibouti' 'Dominica'
 'Dominican Republic' 'El Salvador' 'Equatorial Guinea' 'Eritrea'
 'Eswatini' 'Ethiopia' 'Faeroe Islands' 'Falkland Islands' 'Fiji'
 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Ghana'
 'Gibraltar' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam' 'Guatemala'
 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras' 'Jamaica' 'Jordan'
 'Kenya' 'Kiribati' 'Kosovo' 'Kyrgyzstan' 'Laos' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Macao' 'Madagascar' 'Malawi' 'Maldives' 'Mali' 'Malta'
 'Martinique' 'Mauritania' 'Mauritius' 'Moldova' 'Mongolia' 'Montenegro'
 'Montserrat' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal'
 'New Caledonia' 'Nicaragua' 'Niger' 'Nigeria' 'Niue' 'North Korea'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Puerto Rico'
 'Reunion' 'Rwanda' 'Saint Helena' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'Sao Tome and Principe' 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone'
 'Solomon Islands' 'Somalia' 'South Sudan' 'Sudan' 'Suriname' 'Syria'
 'Tajikistan' 'Tanzania' 'Timor' 'Togo' 'Tonga' 'Tunisia'
 'Turks and Caicos Islands' 'Uganda' 'United States Virgin Islands'
 'Uruguay' 'Vanuatu' 'Western Sahara' 'Yemen' 'Zambia' 'Zimbabwe']

In [6]:
countries_2003_plus_df = countries_df[countries_df['Year'] >= 2003]

In [7]:
countries_2003_plus_df.columns

Index(['Entity', 'Code', 'Year', 'Geo Biomass Other - TWh',
       'Solar Generation - TWh', 'Wind Generation - TWh',
       'Hydro Generation - TWh', 'Electricity from solar (TWh)',
       'Solar Capacity', 'Geothermal Capacity', 'Solar (% electricity)',
       'Wind (% electricity)', 'Hydro (% equivalent primary energy)',
       'Solar (% equivalent primary energy)',
       'Renewables (% equivalent primary energy)',
       'Wind (% equivalent primary energy)', 'Electricity from hydro (TWh)',
       'Biofuels Production - TWh - Total', 'Electricity from wind (TWh)',
       'Other renewables including bioenergy (TWh)', 'Wind Capacity',
       'Hydro (% electricity)', 'Renewables (% electricity)'],
      dtype='object')

In [8]:
countries_2003_plus_df.head(100)

,Entity,Code,Year,Geo Biomass Other - TWh,Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Electricity from solar (TWh),Solar Capacity,Geothermal Capacity,Solar (% electricity),Wind (% electricity),Hydro (% equivalent primary energy),Solar (% equivalent primary energy),Renewables (% equivalent primary energy),Wind (% equivalent primary energy),Electricity from hydro (TWh),Biofuels Production - TWh - Total,Electricity from wind (TWh),Other renewables including bioenergy (TWh),Wind Capacity,Hydro (% electricity),Renewables (% electricity)
152,Algeria,DZA,2003,0.000000,0.000000,0.000000,0.265000,0.00,0.000000,NaN,0.000000,0.000000,0.228104,0.000000,0.228104,0.000000,0.26,NaN,0.00,0.00,NaN,0.934916,0.934916
153,Algeria,DZA,2004,0.000000,0.000000,0.000000,0.251000,0.00,0.000000,NaN,0.000000,0.000000,0.206787,0.000000,0.206787,0.000000,0.25,NaN,0.00,0.00,NaN,0.850630,0.850630
154,Algeria,DZA,2005,0.000000,0.000000,0.000000,0.555300,0.00,0.000000,NaN,0.000000,0.000000,0.434119,0.000000,0.434119,0.000000,0.55,NaN,0.00,0.00,NaN,1.723598,1.723598
155,Algeria,DZA,2006,0.000000,0.000000,0.000000,0.217600,0.00,0.000000,NaN,0.000000,0.000000,0.163272,0.000000,0.163272,0.000000,0.22,NaN,0.00,0.00,NaN,0.664051,0.664051
156,Algeria,DZA,2007,0.000000,0.000000,0.000000,0.226000,0.00,0.000000,NaN,0.000000,0.000000,0.159905,0.000000,0.159905,0.000000,0.22,NaN,0.00,0.00,NaN,0.628931,0.628931
157,Algeria,DZA,2008,0.000000,0.000000,0.000000,0.283000,0.00,0.000000,NaN,0.000000,0.000000,0.187754,0.000000,0.187754,0.000000,0.28,NaN,0.00,0.00,NaN,0.740153,0.740153
158,Algeria,DZA,2009,0.000000,0.000000,0.000000,0.342000,0.00,0.000000,NaN,0.000000,0.000000,0.212785,0.000000,0.212785,0.000000,0.30,NaN,0.00,0.00,NaN,0.828500,0.828500
159,Algeria,DZA,2010,0.000000,0.009100,0.000000,0.173000,0.00,0.000000,NaN,0.000000,0.000000,0.109381,0.005752,0.115132,0.000000,0.17,NaN,0.00,0.00,NaN,0.395349,0.395349
160,Algeria,DZA,2011,0.000000,0.018119,0.000000,0.378000,0.00,0.000000,NaN,0.000000,0.000000,0.224499,0.010761,0.235260,0.000000,0.50,NaN,0.00,0.00,NaN,1.037991,1.037991
161,Algeria,DZA,2012,0.000000,0.026723,0.000000,0.389000,0.00,0.000000,NaN,0.000000,0.000000,0.210099,0.014433,0.224532,0.000000,0.62,NaN,0.00,0.00,NaN,1.148361,1.148361
162,Algeria,DZA,2013,0.000000,0.028600,0.000000,0.099000,0.00,0.000000,NaN,0.000000,0.000000,0.050247,0.014516,0.064763,0.000000,0.33,NaN,0.00,0.00,NaN,0.586042,0.586042
163,Algeria,DZA,2014,0.000000,0.060000,0.001000,0.193000,0.00,0.001100,NaN,0.000000,0.000000,0.089283,0.027757,0.117502,0.000462,0.25,NaN,0.00,0.00,NaN,0.413907,0.413907
164,Algeria,DZA,2015,0.000000,0.058000,0.019000,0.145000,0.06,0.049100,NaN,0.092764,0.030921,0.063234,0.025294,0.096813,0.008286,0.14,NaN,0.02,0.00,NaN,0.216450,0.340136
165,Algeria,DZA,2016,0.000000,0.245000,0.019052,0.072000,0.09,0.219100,NaN,0.134811,0.044937,0.031240,0.106301,0.145807,0.008266,0.22,NaN,0.03,0.00,NaN,0.329539,0.509287
166,Algeria,DZA,2017,0.000000,0.504000,0.019000,0.056000,0.57,0.400000,NaN,0.797203,0.013986,0.023891,0.215021,0.247018,0.008106,0.06,NaN,0.01,0.00,NaN,0.083916,0.895105
167,Algeria,DZA,2018,0.000000,0.603000,0.010000,0.117000,0.65,0.423000,NaN,0.901401,0.013868,0.046108,0.237633,0.287679,0.003939,0.12,NaN,0.01,0.00,NaN,0.166412,1.081681
168,Algeria,DZA,2019,0.000000,0.615000,0.010000,0.152000,0.68,0.423000,NaN,0.886687,0.013040,0.057660,0.233294,0.294747,0.003794,0.15,NaN,0.01,0.00,NaN,0.195593,1.095319
169,Algeria,DZA,2020,0.000000,0.685000,0.007700,0.049600,0.66,0.423000,NaN,0.907341,0.013748,0.019905,0.274904,0.297899,0.003090,0.05,NaN,0.01,0.00,NaN,0.068738,0.989827
170,Algeria,DZA,2021,0.000000,0.664000,0.010500,0.009300,0.81,0.423000,NaN,1.044622,0.012897,0.003554,0.253800,0.261367,0.004013,0.09,NaN,0.01,0.00,NaN,0.116069,1.173588
209,Argentina,ARG,2003,0.880599,0.000065,0.077954,33.800575,0.00,0.000026,NaN,0.000000,0.090765,13.975237,0.000027,14.408259,0.032231,33.47,0.106121,0.08,0.83,0.025729,37.973680,39.006126
210,Argentina,ARG,2004,0.867512,0.000070,0.072446,30.462402,0.00,0.000026,NaN,0.000000,0.073153,11.785715,0.000027,12.185576,0.028029,30.14,0.106412,0.07,0.82,0.027829,31.497543,32.427630
211,Argentina,ARG,2005,0.916500,0.000081,0.071720,34.216137,0.00,0.000026,NaN,0.000000,0.079318,12.392465,0.000029,12.788524,0.025976,33.66,0.106121,0.08,0.86,0.027829,33.372993,34.304974
212,Argentina,ARG,2006,1.046309,0.000090,0.069640,38.015213,0.00,0.000026,NaN,0.000000,0.062837,13.023436,0.000031,13.449462,0.023858,37.57,0.352672,0.07,1.03,0.027829,33.725315,34.712746
213,Argentina,ARG,2007,1.070851,0.000109,0.061593,31.220150,0.00,0.000026,NaN,0.000000,0.054127,10.184650,0.000036,10.599154,0.020093,30.06,2.007858,0.06,1.06,0.027829,27.117727,28.128101
214,Argentina,ARG,2008,1.205980,0.000144,0.041951,31.199696,0.00,0.000026,NaN,0.000000,0.034858,9.985144,0.000046,10.437064,0.013426,30.11,7.112290,0.04,1.13,0.027829,26.239650,27.259260
215,Argentina,ARG,2009,1.188936,0.000076,0.036832,34.618187,0.00,0.000026,NaN,0.000000,0.034394,11.326775,0.000025,11.783506,0.012051,33.53,11.965088,0.04,1.13,0.027829,28.830610,29.836628
216,Argentina,ARG,2010,1.442360,0.000086,0.025352,33.359910,0.00,0.000026,NaN,0.000000,0.025075,10.463687,0.000027,11.661375,0.007952,33.02,19.893944,0.03,1.36,0.027829,27.599464,28.761284
217,Argentina,ARG,2011,1.419131,0.001614,0.026591,31.186930,0.00,0.001252,NaN,0.000000,0.048880,9.461024,0.000489,10.929448,0.008067,31.03,25.844816,0.06,1.34,0.059579,25.279022,26.419552
218,Argentina,ARG,2012,1.484553,0.008173,0.369862,29.164400,0.01,0.006252,NaN,0.007771,0.637190,8.462529,0.002372,10.216426,0.107322,28.71,26.502537,0.82,1.39,0.136979,22.309425,24.034500
219,Argentina,ARG,2013,1.606664,0.015074,0.453355,32.771378,0.01,0.008257,NaN,0.007558,0.763359,9.087360,0.004180,10.950079,0.125713,32.51,23.838686,1.01,1.50,0.189979,24.571081,26.475702
220,Argentina,ARG,2014,1.482859,0.015944,0.619491,32.416695,0.02,0.008252,NaN,0.015173,0.470374,8.962524,0.004408,11.038978,0.171276,32.33,30.584423,0.62,1.40,0.215187,24.527730,26.075413
221,Argentina,ARG,2015,1.517351,0.014683,0.593335,32.337470,0.01,0.008618,NaN,0.007257,0.428188,8.738676,0.003968,10.907397,0.160339,31.94,23.461845,0.59,1.43,0.187104,23.180202,24.653460
222,Argentina,ARG,2016,1.138809,0.014273,0.547359,29.752789,0.01,0.008806,NaN,0.007161,0.386709,8.031665,0.003853,10.167007,0.147758,29.40,32.768284,0.54,1.07,0.187442,21.054140,22.214266
223,Argentina,ARG,2017,1.389037,0.016417,0.611567,31.594284,0.02,0.008806,NaN,0.014433,0.440211,8.488072,0.004411,10.964719,0.164303,31.46,36.231870,0.61,1.31,0.226742,22.703325,24.103342
224,Argentina,ARG,2018,1.589833,0.108130,1.412743,32.278667,0.11,0.191236,NaN,0.078689,1.001502,8.683492,0.029089,11.397630,0.380051,31.96,31.703428,1.40,1.50,0.750342,22.862867,25.016096
225,Argentina,ARG,2019,1.649902,0.799698,4.995966,27.504503,0.79,0.442111,NaN,0.593271,3.717332,7.789057,0.226468,11.926772,1.414818,27.33,28.550030,4.95,1.56,1.609359,20.524181,26.006308
226,Argentina,ARG,2020,2.264699,1.344358,9.410639,23.669312,1.33,0.764135,NaN,0.958973,6.720023,7.057022,0.400821,12.179417,2.805788,24.26,16.743961,9.32,2.14,2.623904,17.492249,26.714254
227,Argentina,ARG,2021,2.103897,2.195563,12.937551,19.597536,2.17,1.071366,NaN,1.479411,8.733297,5.378618,0.602581,11.329249,3.550760,20.19,23.779903,12.81,2.01,3.292124,13.764658,25.347696
380,Australia,AUS,2003,1.691800,0.063200,0.704050,16.210550,0.06,0.039000,NaN,0.028086,0.327669,3.454619,0.013469,4.014969,0.150040,16.13,0.535323,0.70,1.61,0.190000,7.550437,8.659832
381,Australia,AUS,2004,2.815250,0.072950,0.795000,15.686650,0.07,0.046000,NaN,0.031380,0.313803,3.218602,0.014968,4.036561,0.163119,15.89,0.321809,0.70,2.75,0.379000,7.123324,8.701304
382,Australia,AUS,2005,3.871000,0.084050,1.299050,15.465700,0.08,0.052000,NaN,0.037089,0.407974,3.139979,0.017065,4.313553,0.263744,15.16,0.320060,0.88,3.63,0.740000,7.028280,9.156236
383,Australia,AUS,2006,3.932500,0.097500,2.162100,14.945100,0.09,0.061000,NaN,0.040926,0.777591,2.891200,0.018862,4.233413,0.418268,15.77,0.592059,1.71,3.62,0.819000,7.171115,9.635760
384,Australia,AUS,2007,4.275000,0.113750,2.852100,13.048950,0.11,0.070000,NaN,0.047926,1.137156,2.449760,0.021355,3.976723,0.535443,14.20,1.159329,2.61,4.01,1.249000,6.186825,9.119031
385,Australia,AUS,2008,3.696100,0.139200,3.458450,11.815150,0.13,0.082000,NaN,0.056633,1.346112,2.167544,0.025537,3.681326,0.634469,11.79,1.879363,3.09,3.48,1.441000,5.136136,8.054890
386,Australia,AUS,2009,2.786800,0.290242,4.437750,12.642050,0.16,0.329000,NaN,0.068161,1.627332,2.338825,0.053696,3.920266,0.821000,11.68,2.695126,3.82,2.66,1.703000,4.975718,7.804379
387,Australia,AUS,2010,2.441550,0.977648,4.985000,13.746000,0.39,1.088000,NaN,0.166931,2.114454,2.528641,0.179843,4.312805,0.917014,13.50,2.101782,4.94,2.30,1.864000,5.778367,9.044215
388,Australia,AUS,2011,2.573950,2.044547,6.432000,19.572000,1.39,2.470000,NaN,0.577027,2.818714,3.470572,0.362546,5.698981,1.140544,16.69,2.542718,6.79,2.46,2.127000,6.928473,11.345427
389,Australia,AUS,2012,3.097850,2.412000,7.725000,17.036000,2.33,3.796000,NaN,0.998372,3.166509,3.047320,0.431447,5.700209,1.381812,13.98,2.693399,7.39,2.93,2.561000,5.990231,11.410575
390,Australia,AUS,2013,3.331650,3.847400,9.259000,19.089000,3.48,4.565000,NaN,1.513175,4.148187,3.351466,0.675490,6.525869,1.625608,18.12,2.845892,9.54,3.06,3.221000,7.878947,14.870858
391,Australia,AUS,2014,3.546362,4.952000,9.777000,14.484000,4.01,5.284000,NaN,1.659700,4.308597,2.510482,0.858320,5.979823,1.694627,18.34,2.989948,10.41,3.39,3.797000,7.590745,14.962130
392,Australia,AUS,2015,3.678062,6.195524,11.833002,14.086569,5.02,5.943000,NaN,2.174666,4.960146,2.371573,1.043060,6.290021,1.992169,13.32,2.640336,11.45,3.33,4.181000,5.770231,14.347600
393,Australia,AUS,2016,3.627513,7.439775,13.039705,17.629421,6.21,6.686000,NaN,2.523672,5.567521,2.938738,1.240174,7.189176,2.173655,15.02,1.462265,13.70,3.48,4.324000,6.103954,15.609379
394,Australia,AUS,2017,3.561684,8.917557,13.210791,13.499718,8.07,7.352000,NaN,3.229163,5.309912,2.245038,1.483013,6.750127,2.196989,16.04,1.235534,13.27,3.39,4.812000,6.418311,16.313873
395,Australia,AUS,2018,3.588149,12.332544,16.261955,17.311330,9.93,8.623000,NaN,3.965972,5.471683,2.825067,2.012569,8.300061,2.653817,15.80,1.503534,13.70,3.50,5.442000,6.310408,17.145937
396,Australia,AUS,2019,3.467726,18.296988,19.471687,14.020776,14.85,12.967000,NaN,5.943328,7.892419,2.201334,2.872721,8.880722,3.057155,15.60,1.737465,19.72,3.24,6.279000,6.243496,21.375970
397,Australia,AUS,2020,3.410424,23.842660,22.606892,14.420926,23.85,17.342000,NaN,9.505401,8.847794,2.376610,3.929338,10.789811,3.725680,14.76,1.456383,22.20,3.18,8.603000,5.882587,25.503168
398,Australia,AUS,2021,3.344045,31.193806,26.795876,15.996179,28.04,19.074000,NaN,11.349470,10.560188,2.634345,5.137179,12.933532,4.412902,14.76,1.340494,26.09,3.09,8.950600,5.974258,29.134624
437,Austria,AUT,2003,1.711921,0.015000,0.366000,33.214993,0.01,0.023000,NaN,0.017224,0.637272,23.480003,0.010604,25.140518,0.258729,33.21,0.318364,0.37,1.65,0.322000,57.199448,60.695835
438,Austria,AUT,2004,2.059730,0.018000,0.924000,36.762283,0.02,0.027000,NaN,0.032295,1.501696,25.351429,0.012413,27.633785,0.637194,36.76,0.585266,0.93,1.91,0.581000,59.357334,63.975456
439,Austria,AUT,2005,2.440143,0.021018,1.331277,37.095140,0.02,0.021018,NaN,0.031013,2.062335,24.982868,0.014155,27.947860,0.896590,37.10,0.848971,1.33,2.43,0.825219,57.528297,63.389675
440,Austria,AUT,2006,3.254765,0.022387,1.752793,35.656086,0.02,0.022387,NaN,0.032113,2.809891,24.114162,0.015140,28.591210,1.185412,35.66,1.273456,1.75,3.23,0.968269,57.257550,65.285805
441,Austria,AUT,2007,4.079125,0.024238,2.037185,37.054450,0.02,0.024238,NaN,0.031791,3.242728,25.442991,0.016643,30.980610,1.398808,37.05,2.575904,2.04,4.06,0.991159,58.893658,68.621840
442,Austria,AUT,2008,4.177986,0.030120,2.011257,38.329490,0.03,0.030120,NaN,0.046512,3.116279,25.656956,0.020162,31.345478,1.346293,38.33,3.095625,2.01,4.16,0.991974,59.426360,69.038760
443,Austria,AUT,2009,4.294753,0.048914,1.954040,40.896305,0.05,0.048915,NaN,0.075415,2.941176,28.077340,0.033582,34.322514,1.341546,40.90,4.284925,1.95,4.28,1.000985,61.689293,71.161385
444,Austria,AUT,2010,4.500126,0.088813,2.063914,38.363420,0.09,0.088813,NaN,0.132528,3.033427,25.348106,0.058682,31.605642,1.363703,38.36,4.487388,2.06,4.48,1.015828,56.486523,66.249440
445,Austria,AUT,2011,4.572212,0.174070,1.936236,34.237170,0.17,0.174070,NaN,0.273049,3.115965,24.011099,0.122078,30.720795,1.357915,34.24,4.459111,1.94,4.56,1.105966,54.995186,65.708320
446,Austria,AUT,2012,4.691266,0.337483,2.462029,43.847700,0.34,0.337483,NaN,0.494905,3.580786,29.031807,0.223449,35.929344,1.630123,43.85,4.459111,2.46,4.68,1.337150,63.828243,74.716160
447,Austria,AUT,2013,4.710273,0.625974,3.153232,42.016720,0.63,0.625974,NaN,0.975383,4.876916,27.841606,0.414790,35.266674,2.089431,42.02,4.280500,3.15,4.70,1.674538,65.056510,78.185486
448,Austria,AUT,2014,4.561513,0.785246,3.845768,41.007236,0.79,0.785246,NaN,1.282051,6.247972,28.136930,0.538793,36.640297,2.638756,41.01,3.756333,3.85,4.55,2.110275,66.553070,81.467060
449,Austria,AUT,2015,4.662630,0.937098,4.840343,37.156864,0.94,0.937098,NaN,1.519806,7.825384,25.314009,0.638420,34.964077,3.297600,37.16,4.356000,4.84,4.65,2.488726,60.080840,76.944220
450,Austria,AUT,2016,4.795521,1.096016,5.234839,39.971336,1.10,1.096016,NaN,1.685824,8.015326,26.193264,0.718221,35.651855,3.430396,39.97,4.804666,5.23,4.78,2.729996,61.256706,78.283520
451,Austria,AUT,2017,4.933439,1.268971,6.571511,38.293750,1.27,1.268971,NaN,1.883714,9.744884,24.402254,0.808637,34.502872,4.187620,38.29,4.472944,6.57,4.92,2.886698,56.793240,75.719376
452,Austria,AUT,2018,4.943343,1.455132,6.030429,37.637910,1.46,1.455132,NaN,2.244772,9.271217,24.417084,0.943997,34.568928,3.912159,37.64,4.412322,6.03,4.93,3.132713,57.872078,76.968020
453,Austria,AUT,2019,4.668266,1.702093,7.450077,40.825970,1.70,1.702093,NaN,2.399097,10.513689,25.131120,1.047752,35.611378,4.586021,40.83,4.422800,7.45,4.66,3.224117,57.620663,77.109795
454,Austria,AUT,2020,4.601138,2.042934,6.791531,41.998030,2.04,2.042934,NaN,2.948403,9.813557,27.552656,1.340259,38.260670,4.455559,42.00,4.577222,6.79,4.59,3.225985,60.702410,80.098274
455,Austria,AUT,2021,4.392519,2.124906,6.751889,42.851505,2.78,2.691934,NaN,4.152353,10.067215,27.224585,1.350003,37.481792,4.289637,38.75,4.822450,6.74,4.48,3.523985,57.879017,78.790146
469,Azerbaijan,AZE,2003,0.000000,0.000000,0.000000,2.470000,0.00,NaN,NaN,0.000000,0.000000,5.277903,0.000000,5.277903,0.000000,2.44,NaN,0.00,0.00,NaN,12.121213,12.121213
470,Azerbaijan,AZE,2004,0.000000,0.000000,0.000000,2.755000,0.00,NaN,NaN,0.000000,0.000000,5.158582,0.000000,5.158582,0.000000,2.73,NaN,0.00,0.00,NaN,13.323572,13.323572
471,Azerbaijan,AZE,2005,0.000000,0.000000,0.000000,3.009400,0.00,NaN,NaN,0.000000,0.000000,5.165003,0.000000,5.165003,0.000000,2.98,NaN,0.00,0.00,NaN,14.825871,14.825871
472,Azerbaijan,AZE,2006,0.000000,0.000000,0.000000,2.518000,0.00,NaN,NaN,0.000000,0.000000,4.366300,0.000000,4.366300,0.000000,2.49,NaN,0.00,0.00,NaN,11.155914,11.155914
473,Azerbaijan,AZE,2007,0.000000,0.000000,0.000000,2.364000,0.00,NaN,NaN,0.000000,0.000000,4.502970,0.000000,4.502970,0.000000,2.34,NaN,0.00,0.00,NaN,11.331718,11.331718
474,Azerbaijan,AZE,2008,0.000000,0.000000,0.000000,2.232000,0.00,NaN,NaN,0.000000,0.000000,4.184757,0.000000,4.184757,0.000000,2.21,NaN,0.00,0.00,NaN,10.806846,10.806846
475,Azerbaijan,AZE,2009,0.000000,0.000000,0.002100,2.308400,0.00,NaN,NaN,0.000000,0.000000,4.866703,0.000000,4.871128,0.004425,2.29,NaN,0.00,0.00,NaN,12.821948,12.821948
476,Azerbaijan,AZE,2010,0.000000,0.000000,0.000500,3.446300,0.00,NaN,NaN,0.000000,0.000000,7.310371,0.000000,7.311432,0.001061,3.41,NaN,0.00,0.00,NaN,19.211267,19.211267
477,Azerbaijan,AZE,2011,0.000000,0.000000,0.000000,2.675800,0.00,NaN,NaN,0.000000,0.000000,5.077954,0.000000,5.077954,0.000000,2.65,NaN,0.00,0.00,NaN,13.787722,13.787722
478,Azerbaijan,AZE,2012,0.000000,0.000000,0.000000,1.821000,0.00,NaN,NaN,0.000000,0.000000,3.337346,0.000000,3.337346,0.000000,1.80,NaN,0.00,0.00,NaN,8.294930,8.294930
479,Azerbaijan,AZE,2013,0.067000,0.000800,0.000800,1.489100,0.00,NaN,NaN,0.000000,0.000000,2.638793,0.001418,2.780693,0.001418,1.47,NaN,0.00,0.00,NaN,6.672719,6.672719
480,Azerbaijan,AZE,2014,0.087000,0.002900,0.002300,1.299700,0.00,NaN,NaN,0.000000,0.000000,2.247366,0.005018,2.433617,0.003971,1.29,NaN,0.00,0.00,NaN,5.531733,5.531733
481,Azerbaijan,AZE,2015,0.090900,0.004600,0.004600,1.637500,0.00,NaN,NaN,0.000000,0.000000,2.573860,0.007231,2.757688,0.007231,1.62,NaN,0.00,0.00,NaN,6.958763,6.958763
482,Azerbaijan,AZE,2016,0.087250,0.035300,0.022800,1.959300,0.04,NaN,NaN,0.169707,0.084854,3.090183,0.055675,3.345908,0.035960,1.94,NaN,0.02,0.00,NaN,8.230802,8.485363
483,Azerbaijan,AZE,2017,0.085150,0.037200,0.022100,1.746400,0.04,NaN,NaN,0.174216,0.087108,2.791737,0.059467,3.049804,0.035328,1.73,NaN,0.02,0.00,NaN,7.534843,7.796167
484,Azerbaijan,AZE,2018,0.081100,0.039260,0.082700,1.768000,0.04,NaN,NaN,0.167926,0.335852,2.730660,0.060637,3.070157,0.127729,1.75,NaN,0.08,0.00,NaN,7.346767,7.850546
485,Azerbaijan,AZE,2019,0.097950,0.044200,0.105400,1.564800,0.04,NaN,NaN,0.162602,0.406504,2.283222,0.064493,2.674584,0.153791,1.55,NaN,0.10,0.00,NaN,6.300813,6.869919
486,Azerbaijan,AZE,2020,0.100300,0.047000,0.096100,1.069500,0.05,NaN,NaN,0.205086,0.410172,1.583463,0.069586,1.975832,0.142282,1.07,NaN,0.10,0.00,NaN,4.388844,5.004102
487,Azerbaijan,AZE,2021,0.096600,0.055200,0.091400,1.277300,0.05,NaN,NaN,0.190186,0.342335,1.823925,0.078823,2.201543,0.130515,1.28,NaN,0.09,0.00,NaN,4.868771,5.401293
525,Bangladesh,BGD,2003,0.000000,0.000900,0.000000,0.749000,0.00,NaN,NaN,0.000000,0.000000,1.276869,0.001535,1.278404,0.000000,1.12,NaN,0.00,0.00,NaN,6.024744,6.024744
526,Bangladesh,BGD,2004,0.000000,0.001900,0.000000,0.749000,0.00,NaN,NaN,0.000000,0.000000,1.226587,0.003110,1.229696,0.000000,1.21,NaN,0.00,0.00,NaN,5.202064,5.202064
527,Bangladesh,BGD,2005,0.000000,0.003400,0.000000,0.749000,0.00,NaN,NaN,0.000000,0.000000,1.130222,0.005123,1.135346,0.000000,1.28,NaN,0.00,0.00,NaN,5.033425,5.033425
528,Bangladesh,BGD,2006,0.000000,0.005400,0.001600,0.749000,0.01,NaN,NaN,0.034188,0.000000,1.036622,0.007472,1.046310,0.002216,1.38,NaN,0.00,0.00,NaN,4.717949,4.752137
529,Bangladesh,BGD,2007,0.000000,0.009000,0.001600,0.749000,0.02,NaN,NaN,0.068470,0.000000,1.006494,0.012092,1.020737,0.002152,0.74,NaN,0.00,0.00,NaN,2.533379,2.601849

In [9]:
countries_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7329 entries, 114 to 8996
Data columns (total 23 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Entity                                      7329 non-null   object
 1   Code                                        7329 non-null   object
 2   Year                                        7329 non-null   int64
 3   Geo Biomass Other - TWh                     4230 non-null   float64
 4   Solar Generation - TWh                      4230 non-null   float64
 5   Wind Generation - TWh                       4230 non-null   float64
 6   Hydro Generation - TWh                      4292 non-null   float64
 7   Electricity from solar (TWh)                7227 non-null   float64
 8   Solar Capacity                              1243 non-null   float64
 9   Geothermal Capacity                         576 non-null    float64
 10  Solar (% electricity)                       5781 non-null   float64
 11  Wind (% electricity)                        5781 non-null   float64
 12  Hydro (% equivalent primary energy)         4292 non-null   float64
 13  Solar (% equivalent primary energy)         4230 non-null   float64
 14  Renewables (% equivalent primary energy)    4292 non-null   float64
 15  Wind (% equivalent primary energy)          4230 non-null   float64
 16  Electricity from hydro (TWh)                7285 non-null   float64
 17  Biofuels Production - TWh - Total           800 non-null    float64
 18  Electricity from wind (TWh)                 7217 non-null   float64
 19  Other renewables including bioenergy (TWh)  7151 non-null   float64
 20  Wind Capacity                               1143 non-null   float64
 21  Hydro (% electricity)                       5830 non-null   float64
 22  Renewables (% electricity)                  5781 non-null   float64
dtypes: float64(20), int64(1), object(2)
memory usage: 1.3+ MB

# WORLD BANK DATA API CALLS

In [42]:
import pandas as pd
import requests

# Define indicators and years
indicators = {
    #ENERGY / CLIMATE
    'EG.USE.PCAP.KG.OE': 'Energy use (kg of oil equivalent per capita)',
    'EG.FEC.RNEW.ZS': 'Renewable energy consumption (% of total final energy consumption)',
    # 'EG.ELC.SOLR.Z': 'Solar energy generation (TWh)',
    # 'EG.ELC.WIND.Z': 'Wind energy generation (TWh)',
    # 'EG.ELC.HYRO.Z': 'Hydropower generation (TWh)',
    # 'EG.ELC.RNWX.Z': 'Electricity generation from renewable sources (TWh)',
    'EN.ATM.CO2E.PC': 'CO2 emissions (metric tons per capita)',
    # 'EN.ATM.CO2E.GD.Z': 'CO2 emissions from electricity and heat production (% of total emissions)',
    'EG.ELC.RNEW.ZS': 'Renewable electricity output (% of total electricity output)',
    'NY.GDP.MKTP.CD': 'GDP (current US$)',
    'EG.IMP.CONS.ZS': 'Energy imports, net (% of energy use)',
    'IC.BUS.EASE.XQ': 'Ease of doing business score (0 = lowest performance to 100 = best performance)',
    'IC.REG.PROC': 'Number of procedures to register a business',
    'IT.CEL.SETS': 'Investment in renewable energy (USD)',
    'EG.USE.COMM.FO.ZS': 'Fossil fuel energy consumption (% of total)',
    'EG.ELC.ACCS.ZS': 'Access to electricity (% of population)',
    'EN.CO2.TRAN.ZS': 'CO2 emissions from transport (% of total fuel combustion)',
    'EN.ATM.GHGT.KT.CE': 'Total greenhouse gas emissions (kt of CO2 equivalent)',
    'EN.CO2.BLDG.ZS': 'CO2 emissions from residential buildings (% of total fuel combustion)',
    'NV.IND.TOTL.KD': 'Industry (including construction), value added (constant LCU)',
    'SP.RUR.TOTL.ZS': 'Rural population (% of population)',
    # 'EP.PMP.SGAS.CD': 'Energy intensity (kg of oil equivalent per unit of GDP)',
    'SP.POP.TOTL': 'Total Population',
    'SP.POP.GROW': 'Population Growth (annual %)',
    'SP.POP.65UP.TO.ZS': 'Population Ages 65 and Above (% of total)',
    'SP.POP.1564.TO.ZS': 'Population Ages 15-64 (% of total)',
    'SP.POP.0014.TO.ZS': 'Population Ages 0-14 (% of total)',
    'IS.VEH.NVEH.P3': 'New Vehicle Registrations (per 1,000 people)',
    'IS.VEH.PCAR.P3': 'Passenger Car Registrations (per 1,000 people)',
    'IS.AIR.PSGR': 'Air Transport, Passengers Carried',
    # 'IE.CPI.ELEC': 'Electricity Price Index',
    'EG.USE.ELEC.KH.PC': 'Electric Power Consumption (kWh per capita)',
    'AG.LND.TOTL.K2': 'Total Land Area (sq. km)',
    # 'AG.LND.INDU.K2': 'Industrial Land Area (sq. km)',
    'IC.BUS.NDNS.ZS': 'Industrial Buildings (% of non-dwelling stock)',
    'NV.IND.TOTL.ZS': 'Industry (including construction), Value Added (% of GDP)'
}

years = list(range(1985, 2023))

# Initialize an empty dataframe to store the final result
master_df = pd.DataFrame()

# Function to fetch data from the World Bank API
def fetch_world_bank_data(indicator, start_year, end_year):
    url = f"http://api.worldbank.org/v2/country/all/indicator/{indicator}?date={start_year}:{end_year}&format=json&per_page=10000"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error fetching data for indicator {indicator}")
        return None

# Set of valid country codes (real countries, no regions or groups)
valid_country_codes = set([
    'AF', 'AL', 'DZ', 'AO', 'AR', 'AM', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 
    'BA', 'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'KH', 'CM', 'CA', 'CV', 'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CD', 
    'CR', 'CI', 'HR', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'ET', 'FJ', 'FI', 'FR', 
    'GA', 'GM', 'GE', 'DE', 'GH', 'GR', 'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 
    'IE', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 
    'LT', 'LU', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MR', 'MU', 'MX', 'MD', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NA', 'NP', 
    'NL', 'NZ', 'NI', 'NE', 'NG', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 
    'RW', 'WS', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SK', 'SI', 'SB', 'ZA', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 
    'SY', 'TJ', 'TZ', 'TH', 'TL', 'TG', 'TO', 'TT', 'TN', 'TR', 'TM', 'UG', 'UA', 'AE', 'GB', 'US', 'UY', 'UZ', 'VU', 
    'VE', 'VN', 'YE', 'ZM', 'ZW'
])


# Loop over each indicator
for indicator_code, indicator_name in indicators.items():
    # Fetch data from the API
    data = fetch_world_bank_data(indicator_code, 1985, 2023)
    
    if data and len(data) > 1:
        # Normalize the data and store it into a dataframe
        df = pd.json_normalize(data[1])
        
        # Retain only relevant columns (country code, country name, year, and value)
        df = df[['country.id', 'country.value', 'date', 'value']]
        
        # Rename the columns for clarity
        df.columns = ['Country Code', 'Country', 'Year', indicator_name]
        
        # Keep only rows that are actual countries (i.e., no regions, groups, or descriptive labels)
        df = df[df['Country Code'].isin(valid_country_codes)]
        
        # Merge the data into the master dataframe
        if master_df.empty:
            master_df = df
        else:
            master_df = pd.merge(master_df, df, on=['Country Code', 'Country', 'Year'], how='outer')
    else:
        print(f"No data returned for indicator: {indicator_name}")

# Convert 'Year' column to integer
master_df['Year'] = master_df['Year'].astype(int)

# Filter for the specified years only
master_df = master_df[master_df['Year'].isin(years)]

No data returned for indicator: CO2 emissions (metric tons per capita)
No data returned for indicator: CO2 emissions from transport (% of total fuel combustion)
No data returned for indicator: Total greenhouse gas emissions (kt of CO2 equivalent)
No data returned for indicator: CO2 emissions from residential buildings (% of total fuel combustion)

In [43]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6399 entries, 1 to 6567
Data columns (total 27 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Country Code                                                                     6399 non-null   object
 1   Country                                                                          6399 non-null   object
 2   Year                                                                             6399 non-null   int64
 3   Energy use (kg of oil equivalent per capita)                                     3831 non-null   float64
 4   Renewable energy consumption (% of total final energy consumption)               5383 non-null   float64
 5   Renewable electricity output (% of total electricity output)                     4380 non-null   float64
 6   GDP (current US$)                                                                6161 non-null   float64
 7   Energy imports, net (% of energy use)                                            3718 non-null   float64
 8   Ease of doing business score (0 = lowest performance to 100 = best performance)  167 non-null    float64
 9   Number of procedures to register a business                                      2624 non-null   float64
 10  Investment in renewable energy (USD)                                             6264 non-null   float64
 11  Fossil fuel energy consumption (% of total)                                      3733 non-null   float64
 12  Access to electricity (% of population)                                          4890 non-null   float64
 13  Industry (including construction), value added (constant LCU)                    5262 non-null   float64
 14  Rural population (% of population)                                               6399 non-null   float64
 15  Total Population                                                                 6399 non-null   float64
 16  Population Growth (annual %)                                                     6397 non-null   float64
 17  Population Ages 65 and Above (% of total)                                        6399 non-null   float64
 18  Population Ages 15-64 (% of total)                                               6399 non-null   float64
 19  Population Ages 0-14 (% of total)                                                6399 non-null   float64
 20  New Vehicle Registrations (per 1,000 people)                                     0 non-null      float64
 21  Passenger Car Registrations (per 1,000 people)                                   0 non-null      float64
 22  Air Transport, Passengers Carried                                                5142 non-null   float64
 23  Electric Power Consumption (kWh per capita)                                      3689 non-null   float64
 24  Total Land Area (sq. km)                                                         6009 non-null   float64
 25  Industrial Buildings (% of non-dwelling stock)                                   2082 non-null   float64
 26  Industry (including construction), Value Added (% of GDP)                        5544 non-null   float64
dtypes: float64(24), int64(1), object(2)
memory usage: 1.4+ MB

In [44]:
master_df['Year'].min()

1985

In [45]:
len(list(set(master_df.Country)))

169

In [46]:
master_df.head(25)

,Country Code,Country,Year,Energy use (kg of oil equivalent per capita),Renewable energy consumption (% of total final energy consumption),Renewable electricity output (% of total electricity output),GDP (current US$),"Energy imports, net (% of energy use)",Ease of doing business score (0 = lowest performance to 100 = best performance),Number of procedures to register a business,Investment in renewable energy (USD),Fossil fuel energy consumption (% of total),Access to electricity (% of population),"Industry (including construction), value added (constant LCU)",Rural population (% of population),Total Population,Population Growth (annual %),Population Ages 65 and Above (% of total),Population Ages 15-64 (% of total),Population Ages 0-14 (% of total),"New Vehicle Registrations (per 1,000 people)","Passenger Car Registrations (per 1,000 people)","Air Transport, Passengers Carried",Electric Power Consumption (kWh per capita),Total Land Area (sq. km),Industrial Buildings (% of non-dwelling stock),"Industry (including construction), Value Added (% of GDP)"
1,AF,Afghanistan,2022,NaN,20.0,NaN,1.450216e+10,NaN,NaN,NaN,22800000.0,NaN,85.3,4.188356e+09,73.384,41128771.0,2.534498,2.394340,54.475027,43.130634,NaN,NaN,NaN,NaN,NaN,NaN,16.050368
2,AF,Afghanistan,2021,NaN,20.0,NaN,1.426650e+10,NaN,NaN,NaN,22700000.0,NaN,97.7,4.442711e+09,73.686,40099462.0,2.851358,2.404058,54.171399,43.424543,NaN,NaN,2.932130e+05,NaN,652230.0,NaN,14.273657
3,AF,Afghanistan,2020,NaN,18.2,NaN,1.995593e+10,NaN,NaN,NaN,22700000.0,NaN,97.7,5.095363e+09,73.974,38972230.0,3.134747,2.416953,53.775135,43.807912,NaN,NaN,4.490410e+05,NaN,652230.0,NaN,12.952600
4,AF,Afghanistan,2019,NaN,18.9,NaN,1.879944e+10,NaN,173.0,4.0,22600000.0,NaN,97.7,5.342745e+09,74.246,37769499.0,2.908529,2.417754,53.290894,44.291352,NaN,NaN,1.066747e+06,NaN,652230.0,NaN,14.058112
5,AF,Afghanistan,2018,NaN,18.3,NaN,1.805322e+10,NaN,NaN,4.0,22000000.0,NaN,93.4,5.095663e+09,74.505,36686784.0,2.885208,2.407093,52.884462,44.708445,NaN,NaN,1.125367e+06,NaN,652230.0,0.220291,13.387247
6,AF,Afghanistan,2017,NaN,19.5,NaN,1.875346e+10,NaN,NaN,4.0,23900000.0,NaN,97.7,4.587603e+09,74.750,35643418.0,2.866492,2.399818,52.481567,45.118616,NaN,NaN,1.647425e+06,NaN,652230.0,0.161551,10.051874
7,AF,Afghanistan,2016,NaN,20.2,NaN,1.811657e+10,NaN,NaN,4.0,21600000.0,NaN,97.7,4.200840e+09,74.980,34636207.0,2.581549,2.398990,52.080044,45.520967,NaN,NaN,1.917924e+06,NaN,652230.0,0.135709,10.466808
8,AF,Afghanistan,2015,NaN,17.7,86.050111,1.913422e+10,NaN,NaN,4.0,19700000.0,NaN,71.5,4.233263e+09,75.197,33753499.0,3.121341,2.405816,51.802078,45.792106,NaN,NaN,1.929907e+06,NaN,652230.0,0.128968,22.124042
9,AF,Afghanistan,2014,NaN,19.1,85.323549,2.049713e+10,NaN,NaN,4.0,18400000.0,NaN,89.5,4.063759e+09,75.413,32716210.0,3.657576,2.409162,51.359300,46.231538,NaN,NaN,2.209428e+06,NaN,652230.0,0.146761,21.229663
10,AF,Afghanistan,2013,NaN,16.9,78.636408,2.014642e+10,NaN,NaN,4.0,16800000.0,NaN,68.0,3.954389e+09,75.627,31541209.0,3.466788,2.403285,50.729095,46.867621,NaN,NaN,2.044188e+06,NaN,652230.0,0.199430,20.444605
11,AF,Afghanistan,2012,NaN,15.4,85.909980,1.990733e+10,NaN,NaN,5.0,15300000.0,NaN,69.1,3.763899e+09,75.840,30466479.0,4.077628,2.391985,50.175525,47.432490,NaN,NaN,1.737962e+06,NaN,652230.0,0.232686,21.157807
12,AF,Afghanistan,2011,NaN,12.6,82.487562,1.780510e+10,NaN,NaN,5.0,13800000.0,NaN,43.2,3.537696e+09,76.052,29249157.0,3.689508,2.373882,49.361758,48.264360,NaN,NaN,2.279341e+06,NaN,652230.0,0.259387,22.740252
13,AF,Afghanistan,2010,NaN,15.2,85.986547,1.585667e+10,NaN,NaN,5.0,10200000.0,NaN,42.7,3.221720e+09,76.263,28189672.0,2.894904,2.353431,48.677571,48.968998,NaN,NaN,1.999127e+06,NaN,652230.0,0.346814,21.151421
14,AF,Afghanistan,2009,NaN,16.5,87.176603,1.241615e+10,NaN,NaN,6.0,10500000.0,NaN,48.3,3.031619e+09,76.472,27385307.0,3.561288,2.335292,48.345199,49.319508,NaN,NaN,NaN,NaN,652230.0,0.275917,21.897122
15,AF,Afghanistan,2008,NaN,21.2,68.654822,1.010930e+10,NaN,NaN,6.0,7900000.0,NaN,42.4,2.857130e+09,76.680,26427199.0,2.002333,2.317614,47.791923,49.890463,NaN,NaN,NaN,NaN,652230.0,NaN,26.915628
16,AF,Afghanistan,2007,NaN,28.8,72.000000,9.747886e+09,NaN,NaN,6.0,4670000.0,NaN,38.4,2.701987e+09,76.887,25903301.0,1.793196,2.305712,47.998897,49.695391,NaN,NaN,NaN,NaN,652230.0,NaN,26.882242
17,AF,Afghanistan,2006,NaN,31.9,70.755750,6.971758e+09,NaN,NaN,5.0,2520000.0,NaN,33.5,2.510368e+09,77.093,25442944.0,4.139678,2.302381,48.466944,49.230675,NaN,NaN,NaN,NaN,652230.0,NaN,28.210768
18,AF,Afghanistan,2005,NaN,33.9,74.061810,6.203257e+09,NaN,NaN,5.0,1200000.0,NaN,28.7,2.208518e+09,77.297,24411191.0,3.576508,2.299413,48.085107,49.615481,NaN,NaN,NaN,NaN,652230.0,NaN,26.812099
19,AF,Afghanistan,2004,NaN,44.2,70.890841,5.224897e+09,NaN,NaN,5.0,600000.0,NaN,23.8,1.954584e+09,77.500,23553551.0,3.933178,2.296647,47.781316,49.922036,NaN,NaN,NaN,NaN,652230.0,NaN,26.226790
20,AF,Afghanistan,2003,NaN,36.7,70.249729,4.520947e+09,NaN,NaN,NaN,200000.0,NaN,19.0,1.663814e+09,77.647,22645130.0,7.541019,2.293913,47.744656,49.961431,NaN,NaN,NaN,NaN,652230.0,NaN,22.710864
21,AF,Afghanistan,2002,NaN,37.8,79.063971,3.825701e+09,NaN,NaN,NaN,25000.0,NaN,14.1,1.508859e+09,77.739,21000256.0,6.449321,2.288834,47.767545,49.943621,NaN,NaN,NaN,NaN,652230.0,NaN,23.810127
22,AF,Afghanistan,2001,NaN,45.6,72.811460,2.813572e+09,NaN,NaN,NaN,0.0,NaN,9.3,NaN,77.831,19688632.0,0.742517,2.284846,47.849204,49.865949,NaN,NaN,NaN,NaN,652230.0,NaN,NaN
23,AF,Afghanistan,2000,NaN,45.0,74.989094,3.521418e+09,NaN,NaN,NaN,0.0,NaN,4.4,NaN,77.922,19542982.0,1.443803,2.284807,47.996934,49.718258,NaN,NaN,1.497050e+05,NaN,652230.0,NaN,NaN
24,AF,Afghanistan,1999,NaN,43.4,73.722628,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,78.014,19262847.0,4.077879,2.285350,48.199164,49.515486,NaN,NaN,1.402000e+05,NaN,652230.0,NaN,NaN
25,AF,Afghanistan,1998,NaN,38.0,74.436090,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,78.105,18493132.0,3.882931,2.285878,48.445150,49.268972,NaN,NaN,5.270000e+04,NaN,652230.0,NaN,NaN

In [139]:
final_df = pd.merge(left=countries_df, right=master_df, left_on=['Entity','Year'], \
                    right_on=['Country','Year'], how = 'inner',suffixes = ['','_wb'])

In [140]:
#final_df.to_csv('kaggle_plus_worldbank_joined_uncleaned_v2.csv',index=False)

In [141]:
# Convert 'Year' to datetime format if not already
final_df['Year'] = pd.to_datetime(final_df['Year'], format='%Y')

# Temporarily set 'Year' as the index to enable resampling
final_df.set_index('Year', inplace=True)

# Group by 'Entity' and resample by 'Year' with forward-fill
final_df = final_df.groupby('Entity').resample('Y').ffill()

# Reset the index, specifying 'Year' only
final_df.reset_index(level='Year', inplace=True)

# Now set 'Year' and 'Entity' as a MultiIndex if needed
final_df.set_index(['Year', 'Entity'], inplace=True)



# final_df = final_df.assign(Year=final_df['Year']).assign(Entity=final_df['Entity']).set_index(['Year','Entity'])
final_df.head()

,,Code,Geo Biomass Other - TWh,Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Electricity from solar (TWh),Solar Capacity,Geothermal Capacity,Solar (% electricity),Wind (% electricity),Hydro (% equivalent primary energy),Solar (% equivalent primary energy),Renewables (% equivalent primary energy),Wind (% equivalent primary energy),Electricity from hydro (TWh),Biofuels Production - TWh - Total,Electricity from wind (TWh),Other renewables including bioenergy (TWh),Wind Capacity,Hydro (% electricity),Renewables (% electricity),Country Code,Country,Energy use (kg of oil equivalent per capita),Renewable energy consumption (% of total final energy consumption),Renewable electricity output (% of total electricity output),GDP (current US$),"Energy imports, net (% of energy use)",Ease of doing business score (0 = lowest performance to 100 = best performance),Number of procedures to register a business,Investment in renewable energy (USD),Fossil fuel energy consumption (% of total),Access to electricity (% of population),"Industry (including construction), value added (constant LCU)",Rural population (% of population),Total Population,Population Growth (annual %),Population Ages 65 and Above (% of total),Population Ages 15-64 (% of total),Population Ages 0-14 (% of total),"New Vehicle Registrations (per 1,000 people)","Passenger Car Registrations (per 1,000 people)","Air Transport, Passengers Carried",Electric Power Consumption (kWh per capita),Total Land Area (sq. km),Industrial Buildings (% of non-dwelling stock),"Industry (including construction), Value Added (% of GDP)"
Year,Entity,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2000-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.31,NaN,0.0,0.0,NaN,65.957440,65.957440,AF,Afghanistan,NaN,45.0,74.989094,3.521418e+09,NaN,NaN,NaN,0.0,NaN,4.4,NaN,77.922,19542982.0,1.443803,2.284807,47.996934,49.718258,NaN,NaN,149705.0,NaN,652230.0,NaN,NaN
2001-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.50,NaN,0.0,0.0,NaN,84.745766,84.745766,AF,Afghanistan,NaN,45.6,72.811460,2.813572e+09,NaN,NaN,NaN,0.0,NaN,9.3,NaN,77.831,19688632.0,0.742517,2.284846,47.849204,49.865949,NaN,NaN,NaN,NaN,652230.0,NaN,NaN
2002-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.56,NaN,0.0,0.0,NaN,81.159424,81.159424,AF,Afghanistan,NaN,37.8,79.063971,3.825701e+09,NaN,NaN,NaN,25000.0,NaN,14.1,1.508859e+09,77.739,21000256.0,6.449321,2.288834,47.767545,49.943621,NaN,NaN,NaN,NaN,652230.0,NaN,23.810127
2003-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.63,NaN,0.0,0.0,NaN,67.021280,67.021280,AF,Afghanistan,NaN,36.7,70.249729,4.520947e+09,NaN,NaN,NaN,200000.0,NaN,19.0,1.663814e+09,77.647,22645130.0,7.541019,2.293913,47.744656,49.961431,NaN,NaN,NaN,NaN,652230.0,NaN,22.710864
2004-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.56,NaN,0.0,0.0,NaN,62.921350,62.921350,AF,Afghanistan,NaN,44.2,70.890841,5.224897e+09,NaN,NaN,5.0,600000.0,NaN,23.8,1.954584e+09,77.500,23553551.0,3.933178,2.296647,47.781316,49.922036,NaN,NaN,NaN,NaN,652230.0,NaN,26.226790

In [142]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4446 entries, (Timestamp('2000-12-31 00:00:00'), 'Afghanistan') to (Timestamp('2021-12-31 00:00:00'), 'Uruguay')
Data columns (total 47 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Code                                                                             4446 non-null   object
 1   Geo Biomass Other - TWh                                                          2429 non-null   float64
 2   Solar Generation - TWh                                                           2429 non-null   float64
 3   Wind Generation - TWh                                                            2429 non-null   float64
 4   Hydro Generation - TWh                                                           2462 non-null   float64
 5   Electricity from solar (TWh)                                                     4319 non-null   float64
 6   Solar Capacity                                                                   1039 non-null   float64
 7   Geothermal Capacity                                                              561 non-null    float64
 8   Solar (% electricity)                                                            4319 non-null   float64
 9   Wind (% electricity)                                                             4319 non-null   float64
 10  Hydro (% equivalent primary energy)                                              2462 non-null   float64
 11  Solar (% equivalent primary energy)                                              2429 non-null   float64
 12  Renewables (% equivalent primary energy)                                         2462 non-null   float64
 13  Wind (% equivalent primary energy)                                               2429 non-null   float64
 14  Electricity from hydro (TWh)                                                     4358 non-null   float64
 15  Biofuels Production - TWh - Total                                                736 non-null    float64
 16  Electricity from wind (TWh)                                                      4319 non-null   float64
 17  Other renewables including bioenergy (TWh)                                       4319 non-null   float64
 18  Wind Capacity                                                                    958 non-null    float64
 19  Hydro (% electricity)                                                            4358 non-null   float64
 20  Renewables (% electricity)                                                       4319 non-null   float64
 21  Country Code                                                                     4446 non-null   object
 22  Country                                                                          4446 non-null   object
 23  Energy use (kg of oil equivalent per capita)                                     2911 non-null   float64
 24  Renewable energy consumption (% of total final energy consumption)               4095 non-null   float64
 25  Renewable electricity output (% of total electricity output)                     3194 non-null   float64
 26  GDP (current US$)                                                                4368 non-null   float64
 27  Energy imports, net (% of energy use)                                            2835 non-null   float64
 28  Ease of doing business score (0 = lowest performance to 100 = best performance)  150 non-null    float64
 29  Number of procedures to register a business                                      2357 non-null   float64
 30  Investment in renewable energy (USD)                                             4402 non-null   float64
 31  Fossil fuel energy consumption (% of total)                                      2835 non-null   float64
 32  Access to electricity (% of population)                                          3930 non-null   float64
 33  Industry (including construction), value added (constant LCU)                    3870 non-null   float64
 34  Rural population (% of population)                                               4446 non-null   float64
 35  Total Population                                                                 4446 non-null   float64
 36  Population Growth (annual %)                                                     4445 non-null   float64
 37  Population Ages 65 and Above (% of total)                                        4446 non-null   float64
 38  Population Ages 15-64 (% of total)                                               4446 non-null   float64
 39  Population Ages 0-14 (% of total)                                                4446 non-null   float64
 40  New Vehicle Registrations (per 1,000 people)                                     0 non-null      float64
 41  Passenger Car Registrations (per 1,000 people)                                   0 non-null      float64
 42  Air Transport, Passengers Carried                                                3714 non-null   float64
 43  Electric Power Consumption (kWh per capita)                                      2809 non-null   float64
 44  Total Land Area (sq. km)                                                         4305 non-null   float64
 45  Industrial Buildings (% of non-dwelling stock)                                   1849 non-null   float64
 46  Industry (including construction), Value Added (% of GDP)                        4026 non-null   float64
dtypes: float64(44), object(3)
memory usage: 1.6+ MB

In [143]:
final_df.reset_index(inplace=True)

In [144]:
# final_df = final_df.fillna(method='bfill') 
list_of_columns = list(final_df.columns)
for c in list_of_columns:
    final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))

for c in list_of_columns:
    final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))

/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='bfill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))
/var/folders/w7/hv_rlkw14rzdvr6y_71_lbvm0000gn/T/ipykernel_29597/370349327.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  final_df[c] = (final_df.groupby("Entity")[c].apply(lambda group: group.fillna(method='ffill')).reset_index(level=0, drop=True))

In [145]:
# final_df.to_csv('kaggle_plus_worldbank_joined_uncleaned_v4.csv',index=False)

In [146]:
final_df.head()

,Year,Entity,Code,Geo Biomass Other - TWh,Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Electricity from solar (TWh),Solar Capacity,Geothermal Capacity,Solar (% electricity),Wind (% electricity),Hydro (% equivalent primary energy),Solar (% equivalent primary energy),Renewables (% equivalent primary energy),Wind (% equivalent primary energy),Electricity from hydro (TWh),Biofuels Production - TWh - Total,Electricity from wind (TWh),Other renewables including bioenergy (TWh),Wind Capacity,Hydro (% electricity),Renewables (% electricity),Country Code,Country,Energy use (kg of oil equivalent per capita),Renewable energy consumption (% of total final energy consumption),Renewable electricity output (% of total electricity output),GDP (current US$),"Energy imports, net (% of energy use)",Ease of doing business score (0 = lowest performance to 100 = best performance),Number of procedures to register a business,Investment in renewable energy (USD),Fossil fuel energy consumption (% of total),Access to electricity (% of population),"Industry (including construction), value added (constant LCU)",Rural population (% of population),Total Population,Population Growth (annual %),Population Ages 65 and Above (% of total),Population Ages 15-64 (% of total),Population Ages 0-14 (% of total),"New Vehicle Registrations (per 1,000 people)","Passenger Car Registrations (per 1,000 people)","Air Transport, Passengers Carried",Electric Power Consumption (kWh per capita),Total Land Area (sq. km),Industrial Buildings (% of non-dwelling stock),"Industry (including construction), Value Added (% of GDP)"
0,2000-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.31,NaN,0.0,0.0,NaN,65.957440,65.957440,AF,Afghanistan,NaN,45.0,74.989094,3.521418e+09,NaN,173.0,5.0,0.0,NaN,4.4,1.508859e+09,77.922,19542982.0,1.443803,2.284807,47.996934,49.718258,NaN,NaN,149705.0,NaN,652230.0,0.275917,23.810127
1,2001-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.50,NaN,0.0,0.0,NaN,84.745766,84.745766,AF,Afghanistan,NaN,45.6,72.811460,2.813572e+09,NaN,173.0,5.0,0.0,NaN,9.3,1.508859e+09,77.831,19688632.0,0.742517,2.284846,47.849204,49.865949,NaN,NaN,1999127.0,NaN,652230.0,0.275917,23.810127
2,2002-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.56,NaN,0.0,0.0,NaN,81.159424,81.159424,AF,Afghanistan,NaN,37.8,79.063971,3.825701e+09,NaN,173.0,5.0,25000.0,NaN,14.1,1.508859e+09,77.739,21000256.0,6.449321,2.288834,47.767545,49.943621,NaN,NaN,1999127.0,NaN,652230.0,0.275917,23.810127
3,2003-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.63,NaN,0.0,0.0,NaN,67.021280,67.021280,AF,Afghanistan,NaN,36.7,70.249729,4.520947e+09,NaN,173.0,5.0,200000.0,NaN,19.0,1.663814e+09,77.647,22645130.0,7.541019,2.293913,47.744656,49.961431,NaN,NaN,1999127.0,NaN,652230.0,0.275917,22.710864
4,2004-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.56,NaN,0.0,0.0,NaN,62.921350,62.921350,AF,Afghanistan,NaN,44.2,70.890841,5.224897e+09,NaN,173.0,5.0,600000.0,NaN,23.8,1.954584e+09,77.500,23553551.0,3.933178,2.296647,47.781316,49.922036,NaN,NaN,1999127.0,NaN,652230.0,0.275917,26.226790

In [147]:
final_df.drop(columns=['New Vehicle Registrations (per 1,000 people)','Passenger Car Registrations (per 1,000 people)',\
                       'Geothermal Capacity','Solar Capacity','Wind Capacity','Biofuels Production - TWh - Total'],inplace=True)

In [148]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4446 entries, 0 to 4445
Data columns (total 43 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Year                                                                             4446 non-null   datetime64[ns]
 1   Entity                                                                           4446 non-null   object
 2   Code                                                                             4446 non-null   object
 3   Geo Biomass Other - TWh                                                          2494 non-null   float64
 4   Solar Generation - TWh                                                           2494 non-null   float64
 5   Wind Generation - TWh                                                            2494 non-null   float64
 6   Hydro Generation - TWh                                                           2494 non-null   float64
 7   Electricity from solar (TWh)                                                     4446 non-null   float64
 8   Solar (% electricity)                                                            4446 non-null   float64
 9   Wind (% electricity)                                                             4446 non-null   float64
 10  Hydro (% equivalent primary energy)                                              2494 non-null   float64
 11  Solar (% equivalent primary energy)                                              2494 non-null   float64
 12  Renewables (% equivalent primary energy)                                         2494 non-null   float64
 13  Wind (% equivalent primary energy)                                               2494 non-null   float64
 14  Electricity from hydro (TWh)                                                     4446 non-null   float64
 15  Electricity from wind (TWh)                                                      4446 non-null   float64
 16  Other renewables including bioenergy (TWh)                                       4446 non-null   float64
 17  Hydro (% electricity)                                                            4446 non-null   float64
 18  Renewables (% electricity)                                                       4446 non-null   float64
 19  Country Code                                                                     4446 non-null   object
 20  Country                                                                          4446 non-null   object
 21  Energy use (kg of oil equivalent per capita)                                     4106 non-null   float64
 22  Renewable energy consumption (% of total final energy consumption)               4446 non-null   float64
 23  Renewable electricity output (% of total electricity output)                     4446 non-null   float64
 24  GDP (current US$)                                                                4446 non-null   float64
 25  Energy imports, net (% of energy use)                                            3688 non-null   float64
 26  Ease of doing business score (0 = lowest performance to 100 = best performance)  4409 non-null   float64
 27  Number of procedures to register a business                                      4409 non-null   float64
 28  Investment in renewable energy (USD)                                             4446 non-null   float64
 29  Fossil fuel energy consumption (% of total)                                      4069 non-null   float64
 30  Access to electricity (% of population)                                          4446 non-null   float64
 31  Industry (including construction), value added (constant LCU)                    4402 non-null   float64
 32  Rural population (% of population)                                               4446 non-null   float64
 33  Total Population                                                                 4446 non-null   float64
 34  Population Growth (annual %)                                                     4446 non-null   float64
 35  Population Ages 65 and Above (% of total)                                        4446 non-null   float64
 36  Population Ages 15-64 (% of total)                                               4446 non-null   float64
 37  Population Ages 0-14 (% of total)                                                4446 non-null   float64
 38  Air Transport, Passengers Carried                                                4226 non-null   float64
 39  Electric Power Consumption (kWh per capita)                                      3688 non-null   float64
 40  Total Land Area (sq. km)                                                         4446 non-null   float64
 41  Industrial Buildings (% of non-dwelling stock)                                   4105 non-null   float64
 42  Industry (including construction), Value Added (% of GDP)                        4424 non-null   float64
dtypes: datetime64[ns](1), float64(38), object(4)
memory usage: 1.5+ MB

In [149]:
final_df.head()

,Year,Entity,Code,Geo Biomass Other - TWh,Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Electricity from solar (TWh),Solar (% electricity),Wind (% electricity),Hydro (% equivalent primary energy),Solar (% equivalent primary energy),Renewables (% equivalent primary energy),Wind (% equivalent primary energy),Electricity from hydro (TWh),Electricity from wind (TWh),Other renewables including bioenergy (TWh),Hydro (% electricity),Renewables (% electricity),Country Code,Country,Energy use (kg of oil equivalent per capita),Renewable energy consumption (% of total final energy consumption),Renewable electricity output (% of total electricity output),GDP (current US$),"Energy imports, net (% of energy use)",Ease of doing business score (0 = lowest performance to 100 = best performance),Number of procedures to register a business,Investment in renewable energy (USD),Fossil fuel energy consumption (% of total),Access to electricity (% of population),"Industry (including construction), value added (constant LCU)",Rural population (% of population),Total Population,Population Growth (annual %),Population Ages 65 and Above (% of total),Population Ages 15-64 (% of total),Population Ages 0-14 (% of total),"Air Transport, Passengers Carried",Electric Power Consumption (kWh per capita),Total Land Area (sq. km),Industrial Buildings (% of non-dwelling stock),"Industry (including construction), Value Added (% of GDP)"
0,2000-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.31,0.0,0.0,65.957440,65.957440,AF,Afghanistan,NaN,45.0,74.989094,3.521418e+09,NaN,173.0,5.0,0.0,NaN,4.4,1.508859e+09,77.922,19542982.0,1.443803,2.284807,47.996934,49.718258,149705.0,NaN,652230.0,0.275917,23.810127
1,2001-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.50,0.0,0.0,84.745766,84.745766,AF,Afghanistan,NaN,45.6,72.811460,2.813572e+09,NaN,173.0,5.0,0.0,NaN,9.3,1.508859e+09,77.831,19688632.0,0.742517,2.284846,47.849204,49.865949,1999127.0,NaN,652230.0,0.275917,23.810127
2,2002-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.56,0.0,0.0,81.159424,81.159424,AF,Afghanistan,NaN,37.8,79.063971,3.825701e+09,NaN,173.0,5.0,25000.0,NaN,14.1,1.508859e+09,77.739,21000256.0,6.449321,2.288834,47.767545,49.943621,1999127.0,NaN,652230.0,0.275917,23.810127
3,2003-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.63,0.0,0.0,67.021280,67.021280,AF,Afghanistan,NaN,36.7,70.249729,4.520947e+09,NaN,173.0,5.0,200000.0,NaN,19.0,1.663814e+09,77.647,22645130.0,7.541019,2.293913,47.744656,49.961431,1999127.0,NaN,652230.0,0.275917,22.710864
4,2004-12-31,Afghanistan,AFG,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.56,0.0,0.0,62.921350,62.921350,AF,Afghanistan,NaN,44.2,70.890841,5.224897e+09,NaN,173.0,5.0,600000.0,NaN,23.8,1.954584e+09,77.500,23553551.0,3.933178,2.296647,47.781316,49.922036,1999127.0,NaN,652230.0,0.275917,26.226790

In [152]:
final_df = final_df[['Year','Entity',\
                     # 'Renewables (% equivalent primary energy)', 
                     'Renewables (% electricity)',\
                     'Renewable energy consumption (% of total final energy consumption)',\
                    'Renewable electricity output (% of total electricity output)',\
                     'Energy use (kg of oil equivalent per capita)', 'GDP (current US$)', 'Energy imports, net (% of energy use)', \
                     'Investment in renewable energy (USD)', 'Total Population', 'Population Ages 65 and Above (% of total)', \
                     'Population Ages 15-64 (% of total)', 'Population Ages 0-14 (% of total)', 'Rural population (% of population)', \
                     'Access to electricity (% of population)', 'Industry (including construction), Value Added (% of GDP)']]

In [153]:
final_df.groupby("Entity").apply(lambda group: group.isnull().sum())

,Year,Entity,Renewables (% electricity),Renewable energy consumption (% of total final energy consumption),Renewable electricity output (% of total electricity output),Energy use (kg of oil equivalent per capita),GDP (current US$),"Energy imports, net (% of energy use)",Investment in renewable energy (USD),Total Population,Population Ages 65 and Above (% of total),Population Ages 15-64 (% of total),Population Ages 0-14 (% of total),Rural population (% of population),Access to electricity (% of population),"Industry (including construction), Value Added (% of GDP)"
Entity,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Albania,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Algeria,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Angola,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Argentina,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Armenia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Australia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Austria,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Azerbaijan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Bahrain,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Bangladesh,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Barbados,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Belarus,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Belgium,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Belize,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Benin,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Bhutan,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Bolivia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Bosnia and Herzegovina,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Botswana,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Brazil,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Bulgaria,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Burkina Faso,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Burundi,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Cambodia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cameroon,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Canada,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Central African Republic,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Chad,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Chile,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
China,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Colombia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Comoros,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Costa Rica,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cote d'Ivoire,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Croatia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cyprus,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Czechia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Denmark,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Djibouti,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Dominica,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Dominican Republic,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Ecuador,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
El Salvador,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Equatorial Guinea,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Eritrea,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Estonia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Ethiopia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Fiji,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Finland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
France,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gabon,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Georgia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Germany,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Ghana,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Greece,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Grenada,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Guatemala,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Guinea,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Guinea-Bissau,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Guyana,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Haiti,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Honduras,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Hungary,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Iceland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
India,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Indonesia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Iraq,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Ireland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Israel,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Italy,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jamaica,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Japan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jordan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Kazakhstan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Kenya,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Kiribati,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,22
Kuwait,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Latvia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Lebanon,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Lesotho,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Liberia,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Libya,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Lithuania,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Luxembourg,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Madagascar,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Malawi,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Malaysia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Maldives,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Mali,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Malta,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Mauritania,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Mauritius,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Mexico,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Moldova,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Mongolia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Montenegro,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Morocco,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Mozambique,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Myanmar,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Namibia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Nepal,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Netherlands,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
New Zealand,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Nicaragua,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Niger,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Nigeria,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Norway,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Oman,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Pakistan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Panama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Papua New Guinea,0,0,0,0,0,32,0,32,0,0,0,0,0,0,0,0
Paraguay,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Peru,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Philippines,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Poland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Portugal,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Qatar,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Romania,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Rwanda,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Samoa,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Sao Tome and Principe,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Saudi Arabia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Senegal,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Serbia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Seychelles,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Sierra Leone,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Singapore,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Slovenia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Solomon Islands,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
South Africa,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Spain,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sri Lanka,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sudan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Suriname,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sweden,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Switzerland,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Tajikistan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Tanzania,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Thailand,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Togo,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Tonga,0,0,0,0,0,0,0,22,0,0,0,0,0,0,0,0
Trinidad and Tobago,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Tunisia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Turkmenistan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Uganda,0,0,0,0,0,22,0,22,0,0,0,0,0,0,0,0
Ukraine,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
United Arab Emirates,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
United Kingdom,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
United States,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Uruguay,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [154]:
null_counts = final_df.groupby("Entity").apply(lambda group: group.isnull().sum())

# Identify categories with > 0 nulls
categories_with_nulls = null_counts[null_counts.sum(axis=1) > 0].index

# Filter out rows belonging to these categories
df_filtered = final_df[~final_df["Entity"].isin(categories_with_nulls)]
df_filtered.head()

,Year,Entity,Renewables (% electricity),Renewable energy consumption (% of total final energy consumption),Renewable electricity output (% of total electricity output),Energy use (kg of oil equivalent per capita),GDP (current US$),"Energy imports, net (% of energy use)",Investment in renewable energy (USD),Total Population,Population Ages 65 and Above (% of total),Population Ages 15-64 (% of total),Population Ages 0-14 (% of total),Rural population (% of population),Access to electricity (% of population),"Industry (including construction), Value Added (% of GDP)"
22,1990-12-31,Albania,86.36364,25.5,86.407767,813.255696,2.028554e+09,7.965058,0.0,3286542.0,5.737989,61.698500,32.563510,63.572,100.0,17.373841
23,1991-12-31,Albania,92.14660,33.0,92.142483,572.781844,1.099559e+09,-2.783624,0.0,3266790.0,5.872114,61.735863,32.392023,63.300,100.0,17.373841
24,1992-12-31,Albania,95.00000,46.8,95.050088,418.286630,6.521750e+08,-3.376251,0.0,3247039.0,6.024280,61.744436,32.231284,62.751,100.0,17.373841
25,1993-12-31,Albania,93.76771,51.1,93.907623,412.378880,1.185315e+09,-0.097756,0.0,3227287.0,6.194681,61.733603,32.071716,62.201,100.0,17.373841
26,1994-12-31,Albania,95.68528,51.4,95.686374,441.249295,1.880951e+09,9.330732,0.0,3207536.0,6.381682,61.713644,31.904675,61.646,100.0,17.373841

In [155]:
df_filtered.groupby('Entity')['Year'].min()

Entity
Albania                  1990-12-31
Algeria                  1985-12-31
Angola                   2000-12-31
Argentina                1985-12-31
Armenia                  2000-12-31
Australia                1985-12-31
Austria                  1985-12-31
Azerbaijan               1985-12-31
Bahrain                  2000-12-31
Bangladesh               1985-12-31
Belarus                  1985-12-31
Belgium                  1985-12-31
Benin                    2000-12-31
Bolivia                  2000-12-31
Bosnia and Herzegovina   2000-12-31
Botswana                 2000-12-31
Brazil                   1985-12-31
Bulgaria                 1985-12-31
Cambodia                 2000-12-31
Cameroon                 2000-12-31
Canada                   1985-12-31
Chile                    1985-12-31
China                    1985-12-31
Colombia                 1985-12-31
Costa Rica               1990-12-31
Cote d'Ivoire            2000-12-31
Croatia                  1990-12-31
Cyprus                   1985-12-31
Czechia                  1985-12-31
Denmark                  1985-12-31
Dominican Republic       2000-12-31
Ecuador                  1985-12-31
El Salvador              1990-12-31
Eritrea                  2000-12-31
Estonia                  1985-12-31
Ethiopia                 1990-12-31
Finland                  1985-12-31
France                   1985-12-31
Gabon                    2000-12-31
Georgia                  2000-12-31
Germany                  1985-12-31
Ghana                    2000-12-31
Greece                   1985-12-31
Guatemala                1990-12-31
Haiti                    2000-12-31
Honduras                 1990-12-31
Hungary                  1985-12-31
Iceland                  1985-12-31
India                    1985-12-31
Indonesia                1985-12-31
Iraq                     1985-12-31
Ireland                  1985-12-31
Israel                   1985-12-31
Italy                    1985-12-31
Jamaica                  2000-12-31
Japan                    1985-12-31
Jordan                   1996-12-31
Kazakhstan               1985-12-31
Kenya                    1990-12-31
Kuwait                   1985-12-31
Latvia                   1985-12-31
Lebanon                  2000-12-31
Libya                    2000-12-31
Lithuania                1985-12-31
Luxembourg               1985-12-31
Malaysia                 1985-12-31
Malta                    1990-12-31
Mauritius                2000-12-31
Mexico                   1985-12-31
Moldova                  2000-12-31
Mongolia                 2000-12-31
Montenegro               2005-12-31
Morocco                  1985-12-31
Mozambique               2000-12-31
Myanmar                  2000-12-31
Namibia                  2000-12-31
Nepal                    2000-12-31
Netherlands              1985-12-31
New Zealand              1985-12-31
Nicaragua                1990-12-31
Niger                    2000-12-31
Nigeria                  2000-12-31
Norway                   1985-12-31
Oman                     1985-12-31
Pakistan                 1985-12-31
Panama                   2000-12-31
Paraguay                 2000-12-31
Peru                     1985-12-31
Philippines              1985-12-31
Poland                   1985-12-31
Portugal                 1985-12-31
Qatar                    1985-12-31
Romania                  1985-12-31
Saudi Arabia             1985-12-31
Senegal                  2000-12-31
Serbia                   1990-12-31
Singapore                1985-12-31
Slovenia                 1990-12-31
South Africa             1985-12-31
Spain                    1985-12-31
Sri Lanka                1985-12-31
Sudan                    2000-12-31
Suriname                 2000-12-31
Sweden                   1985-12-31
Switzerland              1985-12-31
Tajikistan               2000-12-31
Tanzania                 2000-12-31
Thailand                 1985-12-31
Togo                     2000-12-31
Trinidad and Tobago      1985-12-31
Tunisia                  1997-12-31
Turkmenistan             1985-12-31
Ukraine                  1985-12-31
United Arab Emirates     1985-12-31
United Kingdom           1985-12-31
United States            1985-12-31
Uruguay                  2008-12-31
Name: Year, dtype: datetime64[ns]

In [156]:
df_filtered.groupby('Entity')['Year'].max()

Entity
Albania                  2020-12-31
Algeria                  2021-12-31
Angola                   2021-12-31
Argentina                2021-12-31
Armenia                  2021-12-31
Australia                2021-12-31
Austria                  2022-12-31
Azerbaijan               2021-12-31
Bahrain                  2021-12-31
Bangladesh               2021-12-31
Belarus                  2021-12-31
Belgium                  2022-12-31
Benin                    2021-12-31
Bolivia                  2021-12-31
Bosnia and Herzegovina   2021-12-31
Botswana                 2021-12-31
Brazil                   2021-12-31
Bulgaria                 2022-12-31
Cambodia                 2021-12-31
Cameroon                 2021-12-31
Canada                   2021-12-31
Chile                    2021-12-31
China                    2021-12-31
Colombia                 2021-12-31
Costa Rica               2021-12-31
Cote d'Ivoire            2021-12-31
Croatia                  2022-12-31
Cyprus                   2022-12-31
Czechia                  2022-12-31
Denmark                  2022-12-31
Dominican Republic       2021-12-31
Ecuador                  2021-12-31
El Salvador              2021-12-31
Eritrea                  2021-12-31
Estonia                  2022-12-31
Ethiopia                 2021-12-31
Finland                  2022-12-31
France                   2022-12-31
Gabon                    2021-12-31
Georgia                  2021-12-31
Germany                  2022-12-31
Ghana                    2021-12-31
Greece                   2022-12-31
Guatemala                2021-12-31
Haiti                    2021-12-31
Honduras                 2021-12-31
Hungary                  2022-12-31
Iceland                  2021-12-31
India                    2021-12-31
Indonesia                2021-12-31
Iraq                     2021-12-31
Ireland                  2022-12-31
Israel                   2021-12-31
Italy                    2022-12-31
Jamaica                  2021-12-31
Japan                    2021-12-31
Jordan                   2021-12-31
Kazakhstan               2021-12-31
Kenya                    2021-12-31
Kuwait                   2021-12-31
Latvia                   2022-12-31
Lebanon                  2021-12-31
Libya                    2021-12-31
Lithuania                2022-12-31
Luxembourg               2022-12-31
Malaysia                 2021-12-31
Malta                    2022-12-31
Mauritius                2021-12-31
Mexico                   2021-12-31
Moldova                  2021-12-31
Mongolia                 2021-12-31
Montenegro               2021-12-31
Morocco                  2021-12-31
Mozambique               2021-12-31
Myanmar                  2021-12-31
Namibia                  2021-12-31
Nepal                    2021-12-31
Netherlands              2022-12-31
New Zealand              2021-12-31
Nicaragua                2021-12-31
Niger                    2021-12-31
Nigeria                  2021-12-31
Norway                   2021-12-31
Oman                     2021-12-31
Pakistan                 2021-12-31
Panama                   2021-12-31
Paraguay                 2021-12-31
Peru                     2021-12-31
Philippines              2021-12-31
Poland                   2022-12-31
Portugal                 2022-12-31
Qatar                    2021-12-31
Romania                  2022-12-31
Saudi Arabia             2021-12-31
Senegal                  2021-12-31
Serbia                   2021-12-31
Singapore                2021-12-31
Slovenia                 2022-12-31
South Africa             2021-12-31
Spain                    2022-12-31
Sri Lanka                2021-12-31
Sudan                    2021-12-31
Suriname                 2021-12-31
Sweden                   2022-12-31
Switzerland              2021-12-31
Tajikistan               2021-12-31
Tanzania                 2021-12-31
Thailand                 2021-12-31
Togo                     2021-12-31
Trinidad and Tobago      2021-12-31
Tunisia                  2021-12-31
Turkmenistan             2021-12-31
Ukraine                  2021-12-31
United Arab Emirates     2021-12-31
United Kingdom           2021-12-31
United States            2021-12-31
Uruguay                  2021-12-31
Name: Year, dtype: datetime64[ns]

In [158]:
#df_filtered.to_csv('kaggle_plus_worldbank_joined_uncleaned_v4.csv',index=False)

In [159]:
df_filtered[df_filtered.isnull().any(axis=1)]

Empty DataFrame
Columns: [Year, Entity, Renewables (% electricity), Renewable energy consumption (% of total final energy consumption), Renewable electricity output (% of total electricity output), Energy use (kg of oil equivalent per capita), GDP (current US$), Energy imports, net (% of energy use), Investment in renewable energy (USD), Total Population, Population Ages 65 and Above (% of total), Population Ages 15-64 (% of total), Population Ages 0-14 (% of total), Rural population (% of population), Access to electricity (% of population), Industry (including construction), Value Added (% of GDP)]
Index: []